#SQLALCHEMY_DATABASE_URI = 'mysql://root:@127.0.0.1:4080/NatterDB'

#SQLALCHEMY_TRACK_MODIFICATIONS = True

userpass = 'mysql://root:@'
basedir = '127.0.0.1'
dbname = '/rajbase'


SECRET_KEY = "HHDKHDKHSKAHDKASHDKAHSDKJASDHKHDKJGFJGJAS"

SQLALCHEMY_TRACK_MODIFICATIONS = True

SQLALCHEMY_DATABASE_URI = userpass+basedir+dbname

MAIL_SERVER='smtp.gmail.com'
MAIL_USERNAME='dspirit118@gmail.com'
MAIL_PASSWORD='Abdulkereem22'
MAIL_DEFAULT_SENDER = 'Raj Class'
MAIL_PORT=465
MAIL_USE_SSL=True
MAIL_USE_TLS=False


